config/routes.rb
Rails.application.routes.draw do
  
  root to: 'sessions#new' 

  resources :blogs do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
      get :favorited
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments
  end

  resources :users
  resources :relationships, only: [:create, :destroy] 
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversions do
    resources :messages 
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  delegate :name, :icon, :id, to: :user, prefix: true

  belongs_to :blog

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @blog = Blog.find(params[:blog_id])
    
    favorite = current_user.favorites.build(blog_id: params[:blog_id])
    favorite.save
    
    #favorite = current_user.favorites.create(blog_id: params[:blog_id])
    #redirect_to blogs_path, notice: "#{favorite.blog.user_name}さんのブログをお気に入り登録しました"
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    
    favorite = Favorite.find_by(blog_id: params[:blog_id], user_id: current_user.id)
    favorite.destroy
    
    #favorite = current_user.favorites.find_by(id: params[:id]).destroy
    #redirect_to blogs_path, notice: "#{favorite.blog.user_name}さんのブログをお気に入り解除しました"
  end

end

app/views/favorites/_favorite.html.erb
  <% if blog.favorited_by?(current_user) %>
    <%= button_to blog_favorites_path(blog_id: blog.id), method: :delete, class: 'btn favorite-delete',
        remote: true do %>
      <span class="glyphicon glyphicon-ok">お気に入り登録(<%= blog.favorites.count %>)</span>
    <% end %>    
  <% else %>
    <%= button_to blog_favorites_path(blog_id: blog.id), method: :post, class: 'btn favorite-create',
        remote: true do %>
      <span class="glyphicon glyphicon-ok">お気に入り登録(<%= blog.favorites.count %>)</span>
    <% end %>
  <% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @blog.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { blog: @blog }) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @blog.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { blog: @blog }) %>");