config/routes.rb
Rails.application.routes.draw do
  
  root to: 'sessions#new' 

  resources :blogs do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
      get :favorited
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments
  end

  resources :users
  resources :relationships, only: [:create, :destroy] 
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversions do
    resources :messages 
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :icon, ImageUploader

  before_validation { email.downcase! }

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 50 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :blogs, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower 

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :login_check_user, only: [:new, :create, :show]
  before_action :set_user, only: [:show, :destroy, :edit, :update]
  before_action :set_current_user, only: [:show, :destroy, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "アカウント作成しました"
    else
      render :new if @user.invalid?
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "編集しました"
    else
      render :edit if @user.invalid?
    end
  end

  def confirm
  end

  def destroy
    @user.destroy
    redirect_to new_user_path, notice: "アカウント削除しました"
  end

  def show
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :icon, :icon_cache,
                                 :remove_icon, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    if current_user.id == @user.id
    else
      redirect_to user_path(current_user.id), notice: "権限がありません" 
    end

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id%>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model:@user, local:true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user-create">
    <%= form.label :name %><br>
    <%= form.text_field :name, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :email %><br>
    <%= form.email_field :email, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :password %><br>
    <%= form.password_field :password, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :icon %><br>
    <%= form.file_field :icon %><br>
    <%= form.hidden_field :icon_cache %>
  </div>
  <div class="user-create">
    <%= form.submit "アカウント作成", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>アカウント編集</h3>
<%= form_with(model:@user, local:true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user-create">
    <%= form.label :name %><br>
    <%= form.text_field :name, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :email %><br>
    <%= form.email_field :email, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :password %><br>
    <%= form.password_field :password, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, size: 30 %><br>
  </div>
  <div class="user-create">
    <%= form.label :icon %><br>
    <%= form.file_field :icon %><br>
    <%= form.hidden_field :icon_cache %>
  </div>
  <div class="user-create">
    <%= form.submit "アカウント編集", class: "btn btn-success",
        data: { confirm: 'こちらの編集内容で良いですか？' }  %>
  </div>
<% end %>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversions_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
    <li><%= render 'follow_form', user: user %></li> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
  <% end %>
<% end %>

app/views/users/new.html.erb
<h2>ユーザーアカウント作成</h2>
<%= render "form" %>

app/views/users/show.html.erb
<div class="profile-content">
   <h3>プロフィール</h3>
   <div class="user-profile" >
      名前：<span id="user-name"><%= @user.name %></span>
      <%= image_tag @user.icon.thumb.url, id: "user-icon" if @user.icon? %>   
   </div>
   <div class="user-profile">
      アドレス：<span id="user-email"><%= @user.email %></span>
   </div>
   <div class="user-profile">
      <%= button_to edit_user_path(@user.id), method: :get, class:"btn btn-warning" do %>
         <span>編集</span>
      <% end %>
   </div>
   <div class="user-profile">
      <%= button_to user_path, method: :delete, class: "btn btn-danger", data: { confirm: '削除して良いですか？' } do %>
         <span>アカウント削除</span>
      <% end %>
   </div>
</div>

<% unless logged_in? %>
   <p class="information">※ログインして下さい</p>
<% end %>