config/routes.rb
Rails.application.routes.draw do
  
  root to: 'sessions#new' 

  resources :blogs do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
      get :favorited
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments
  end

  resources :users
  resources :relationships, only: [:create, :destroy] 
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversions do
    resources :messages 
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsKadai2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header crearfix">
      <% if logged_in? %>
      <ul>
        <%= link_to user_path(current_user.id) do %>
          <li class="header-link">プロフィール</li>
        <% end %>
        <%= link_to session_path(current_user.id), method: :delete do %>
          <li class="header-link">ログアウト</li>
        <% end %>
        <li class="h-user-name">
          お名前：<%= current_user.name %>さん
        </li>
      <% else %>
        <%= link_to new_user_path do %>
          <li class="header-link">アカウント作成</li>
        <% end %>
        <%= link_to new_session_path do %>
          <li class="header-link">ログイン</li>
        <% end %>
      </ul>
      <% end %>
    </header>
      <% flash.each do |key, value| %>
        <% if key == notice %>
          <%= content_tag(:div, value, class: "alert alert-success") %>
        <% elsif key == alert %>
          <%= content_tag(:div, value, class: "alert alert-danger") %>
        <% else %>
          <%= content_tag(:div, value, class: "alert alert-info") %>
        <% end %>
      <% end %>
    <div class="main">
      <%= yield %>
    </div>
    <footer class="footer crearfix">
      <% if logged_in? %>
      <ul>
        <%= link_to new_blog_path do %>
          <li class="footer-link">投稿作成</li>
        <% end %>
        <%= link_to blogs_path do %>
          <li class="footer-link">投稿一覧</li>
        <% end %>
        <%= link_to favorited_blog_path(current_user.id) do %>
          <li class="footer-link">お気に入り一覧</li>
        <% end %>
        <%= link_to users_path do %>
          <li class="footer-link">ユーザー一覧</li>
        <% end %>
      </ul>
      <% end %>
    </footer>
  </body>
</html>